select POLICY_NAME,MINIMUM_YEAR,MAXIMUM_YEAR,(BONUS_PERCENTAGE+(BONUS_PERCENTAGE*0.1)) AS UPDATED_BONUS 
FROM POLICY 
WHERE POLICY_ID NOT IN 
(select POLICY_ID from policyenrollment) 
ORDER BY POLICY_NAME DESC;